### ISSUE TITLE
Generate email message using AI is not working

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1127]
## Description

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/86da3782-dc6a-4670-b415-1ce22c193136)

Use the "generate message" function, nothing happening in the result of AI.

**Comment by SamuelHassine** [comment]
Tested on https://demo.obas.filigran.io/.

**Comment by jborozco** [comment]
fyi the generation works on testing but not on demo

**Comment by Christian-DONGMO** [comment]
I' m not able to reproduce the bug in dev. It works fine!

**Comment by Dimfacion** [comment]
@Christian-DONGMO From what I understand, we use [reactor](https://projectreactor.io/) which is a mix of pull and push. I noticed [here ](https://github.com/FiligranHQ/platform/blob/817bb0cd0f2238e172978d3f16ffebd3c2c45875/inventories/eu-west-staging/vars/deployments/testing.yml#L16) that testing does whitelist all IPs while demo does not. Could you check with the platform team that it's not the issue here ?
