### ISSUE TITLE
When exporting then importing a scenario, all expectations are lost

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1129]
## Description

When exporting then importing a scenario, all expectations in injects are lost

**Comment by jborozco** [comment]
The problem seems to have been corrected, the expectations have are imported now.  but the tags are not.  

Exported scenario: https://demo.obas.filigran.io/admin/scenarios/fc7ea416-8af3-438a-95dc-68874304da34/injects
Imported scenario: https://demo.obas.filigran.io/admin/scenarios/166f2608-9879-41bc-ab82-a3b66a07fef1/injects

**Comment by savacano28** [comment]
Tags from description are not exported.
