### ISSUE TITLE
Media pressure pages don't show any content

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1378]
## Description

Media pressure pages don't show any content

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Link in ticket comment

**Comment by guillaumejparis** [comment]
From what I understand, it is probablyt by design.
When you preview a media pressure you see this : 


![Image](https://github.com/user-attachments/assets/5adfb94c-84ff-458b-85dc-becf1b302b74)

But if you try to switch to player mode before the inject using this media pressure has been processed you will see this : 


![Image](https://github.com/user-attachments/assets/469c0b02-aaee-4666-8b70-fdfc00744fd9)

As a player the access at the media pressure is blocked until the inject has been processed.

@RomuDeuxfois Can you confirm if this is correct?

**Comment by jborozco** [comment]
Problem solved with serveur migration to mailgun
