### ISSUE TITLE
Caldera injectors checks on results of execution can loop forever

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#874]
## Description

https://testing.obas.staging.filigran.io/admin/atomic_testings/cd79bd00-c064-44f2-9ea3-2e6a4aab90cb/detail

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/038d44a6-08a3-444f-aae8-027478b620d2)

This leads to an infinite loop in the platform.

**Comment by savacano28** [comment]
This is related to set pending status as expired after x time : https://github.com/OpenBAS-Platform/openbas/issues/846 ?

**Comment by SamuelHassine** [comment]
https://testing.obas.staging.filigran.io/admin/atomic_testings/9ee70a84-d148-4ecf-ac8e-c4367685dd64/detail

**Comment by SamuelHassine** [comment]
@savacano28 @jborozco this is not the same... Pending expectations are now expiring through the fake detector. But this is linked to the Caldera injector checking just the results of the execution forever to put the status of the atomic testing or the inject.

**Comment by SamuelHassine** [comment]
@RomuDeuxfois can you please take a look?

**Comment by savacano28** [comment]
The function that retrieves the results checks for injects in a pending status. If we manage these injects within the timeout period, we can avoid the infinite loop. How long should we wait for Caldera's response?

**Comment by RomuDeuxfois** [comment]
**Theory**:
- the agent used to carry out the attack has fallen, so we cannot find a result via Caldera which triggers this exception -> "Caldera failed to get result of the executed ability"

We should put a TimeOut because It is possible that we went faster to make the call than Caldera to log the launch of the attack. And in the next loop we are recovering the result.

**Remaining question**
how do we get the following log "Results are not yet available (still on-going)" afterwards?
Will we launch a new agent for the attack via the sub processor mechanism?
