### ISSUE TITLE
Empower the injects timeline with new interactions

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#877]
## Use case
To simplify injects set up, add new interaction to the timeline:
- When hovering an inject in the timeline: show the exact time of the launch
- Clicking on inject from the timeline should open the inject details in a drawer
- Have a way to hide/show the timeline

**Comment by Lhorus6** [comment]
Small clarification (the description seems misleading): 
It would be useful to have a timeline of the forecasted execution of the injects **in the scenario**. Currently, if we have a lot of injects, it's difficult to visualize the flow of execution and the gap between each inject by looking at the “Trigger” column.

A timeline like the one we have in the “animation” tab of simulations would be appreciated at scenario level, because it's also useful when designing the scenario, and not just for tracking the progress of a running simulation.
